backend:
  name: local

media_folder: "public/uploads"
public_folder: "/uploads"
local_backend: true

collections:
  - name: "gameplay"
    label: "Gameplay Config"
    files:
      - file: "src/content/configs/gameplay.json"
        label: "Gameplay"
        name: "gameplay"
        format: "json"
        fields:
          - { label: "PLAYER_SPEED", name: "PLAYER_SPEED", widget: "number" }
          - { label: "PLAYER_JUMP_MULTIPLICATOR", name: "PLAYER_JUMP_MULTIPLICATOR", widget: "number" }
          - { label: "PLAYER_FALL_MULTIPLICATOR", name: "PLAYER_FALL_MULTIPLICATOR", widget: "number" }
          - { label: "PLAYER_PLATFORM_BODY_WIDTH", name: "PLAYER_PLATFORM_BODY_WIDTH", widget: "number" }
          - { label: "PLAYER_PLATFORM_BODY_HEIGHT", name: "PLAYER_PLATFORM_BODY_HEIGHT", widget: "number" }
          - { label: "PLAYER_TOPDOWN_BODY_WIDTH", name: "PLAYER_TOPDOWN_BODY_WIDTH", widget: "number" }
          - { label: "PLAYER_TOPDOWN_BODY_HEIGHT", name: "PLAYER_TOPDOWN_BODY_HEIGHT", widget: "number" }
          - { label: "PLAYER_DISPLAY_WIDTH", name: "PLAYER_DISPLAY_WIDTH", widget: "number" }
          - { label: "PLAYER_DISPLAY_HEIGHT", name: "PLAYER_DISPLAY_HEIGHT", widget: "number" }
          - { label: "PLAYER_MAX_HEALTH", name: "PLAYER_MAX_HEALTH", widget: "number" }
          - { label: "PLAYER_CURRENT_HEALTH", name: "PLAYER_CURRENT_HEALTH", widget: "number" }
          - { label: "HEAL_VALUE", name: "HEAL_VALUE", widget: "number" }
          - { label: "BOMB_DAMAGE", name: "BOMB_DAMAGE", widget: "number" }